---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/posts/{postId}/comments":
    post:
      summary: Creates a comment
      tags:
      - Comments
      parameters:
      - name: postId
        in: path
        description: ID of the post to add a comment to
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: comment created
        '400':
          description: bad request
        '404':
          description: post not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
servers:
- url: https://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
